MaxFit/mdapioutput/objects/Error_Log__c.object
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>LOG - {000000}</displayFormat>
        <label>Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Log_Details__c</fullName>
        <label>Log Details</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Process_Name__c</fullName>
        <label>Process Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

MaxFit/force-app/main/default/classes/TransactionLogHandler.cls
public class TransactionLogHandler {

    public static void doHandleException(System.Exception ex, string processName){
        Error_Log__c transactionLog = new Error_Log__c(
        	Log_Details__c = ex.getStackTraceString() + ' <br/> ' + ex.getMessage() +
        					' <br/> ' + ex.getCause() + ' <br/> ' + ex.getTypeName() + ' <br/> ' + ex.getLineNumber(),
        	Log_DateTime__c = System.now(),
        	Process_Name__c = processName
        );
        insert transactionLog;
    }
    public static void doHandleExceptionWithError(string errors, string processName){
        Error_Log__c transactionLog = new Error_Log__c(
        	Log_Details__c = errors,
        	Log_DateTime__c = System.now(),
        	Process_Name__c = processName
        );
        insert transactionLog;
    }
}